using Carpare.Models.Transaction;

namespace Carpare.Models.Entity
{
    /// <summary>
    /// Represents the user database as a class.
    /// </summary>
    public class User
    {
        /// <summary>
        /// Username of the user.
        /// </summary>
        public string UserId { get; set; }
        /// <summary>
        /// Name of the user.
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Salt value for the user.
        /// </summary>
        public string Salt { get; set; }
        /// <summary>
        /// E-Mail of the user.
        /// </summary>
        public string email { get; set; }
        /// <summary>
        /// Password hash generated by the C# function for the user.
        /// </summary>
        public string PasswordHash { get; set; }
        /// <summary>
        /// Boolean value to see whether user is admin or not.
        /// </summary>
        public bool IsAdmin { get; set; }
        /// <summary>
        /// Status of the user whether the user is active or inactive.
        /// </summary>
        public string status { get; set; }
        /// <summary>
        /// Gender of the user.
        /// </summary>
        public string gender { get; set; }
        /// <summary>
        /// Birth date of the user.
        /// </summary>
        public string BirthDate { get; set; }
        /// <summary>
        /// Location of the user.
        /// </summary>
        public string Location { get; set; }

        /// <summary>
        /// Initializes an empty user.
        /// </summary>
        public User()
        {
            UserId = "";
            Name = "";
            Salt = "";
            PasswordHash = "";
            email = "";
            IsAdmin = false;
        }

        /// <summary>
        /// Initializes a new user.
        /// </summary>
        /// <param name="UserId">Username of the user.</param>
        /// <param name="Name">Name of the user.</param>
        /// <param name="Salt">Salt value for the user.</param>
        /// <param name="HashedPassword">Password hash generated by the C# function for the user.</param>
        /// <param name="email">E-Mail of the user.</param>
        /// <param name="IsAdmin">Boolean value to see whether user is admin or not.</param>
        /// <param name="stat">Status of the user whether the user is active or inactive.</param>
        /// <param name="gender">Gender of the user.</param>
        /// <param name="date">Birth date of the user.</param>
        /// <param name="loc">Location of the user.</param>
        public User(string UserId, string Name, string Salt, string HashedPassword, string email, bool IsAdmin, string stat, string gender, string date, string loc)
        {
            this.UserId = UserId;
            this.Name = Name;
            this.Salt = Salt;
            PasswordHash = HashedPassword;
            this.email = email;
            this.IsAdmin = IsAdmin;
            status = stat;
            this.gender = gender;
            BirthDate = date;
            Location = loc;
        }

        /// <summary>
        /// Returns the Salt for encryption.
        /// </summary>
        /// <returns>String that is used for salt value.</returns>
        public static string CreateSalt()
        {
            return EncryptionManager.PasswordSalt;
        }

        /// <summary>
        /// Creates a string which is used for printing information about the user on output.
        /// </summary>
        /// <returns>The string contains information about user.</returns>
        public string toString()
        {
            string returnString = "Username: " + UserId + " Name: " + Name + " E-mail: " + email + " IsAdmin: " + IsAdmin + " Status: " + status + " Gender: " + gender
                + " Date: " + BirthDate + " Location: " + Location;
            return returnString;
        }
    }
}